### ISSUE TITLE
[코드 이슈] 이슈 테스트 중입니다.

### ISSUE THREAD

**Issue by 101Jay** [101Jay/The-Habit#1]
## 이슈명
- 이슈가 무엇인지 명확하게 기재해주세요.

이슈 템플릿 테스트 중이라 큰 이슈는 없습니다.

## 이슈 과정
- 어떤 과정에서 이슈를 겪게 되었는지 기재해주세요.

## 원하는 해결 방식
- 어떻게 이 문제가 해결되었으면 좋겠는지 기재해주세요.

## 캡처
- 관련 캡처 이미지가 존재한다면 올려주세요.

## 기타
- 추가로 논의가 필요한 부분에 대해서 기재해주세요.

**Comment by hoiae** [comment]
테스트 완료
